// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "WebBrowser2.h"

/////////////////////////////////////////////////////////////////////////////
// CWebBrowser2

IMPLEMENT_DYNCREATE(CWebBrowser2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CWebBrowser2 properties

/////////////////////////////////////////////////////////////////////////////
// CWebBrowser2 operations

void CWebBrowser2::HideScrollBars()
{
	RECT ierect;
	int cxvs, cyvs;
	GetClientRect(&ierect); 

	cxvs = GetSystemMetrics (SM_CXVSCROLL); 
	cyvs = GetSystemMetrics (SM_CYVSCROLL); 

	SetWindowPos(NULL, ierect.left, ierect.top, ierect.right+cxvs, ierect.bottom+cyvs, SWP_NOMOVE | SWP_NOZORDER);

	ierect.bottom -= ierect.top;
	ierect.right -= ierect.left;

	ierect.top = 0;
	ierect.left = 0;

	HRGN iehrgn = NULL; 

	iehrgn=CreateRectRgn (ierect.left, ierect.top, ierect.right-2, ierect.bottom-2);

	SetWindowRgn (iehrgn, TRUE);
}
