// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ie_webbrower.h"

/////////////////////////////////////////////////////////////////////////////
// CIe_WebBrower

IMPLEMENT_DYNCREATE(CIe_WebBrower, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIe_WebBrower properties

/////////////////////////////////////////////////////////////////////////////
// CIe_WebBrower operations
