#pragma  once

#define		TIMER_MOVE_POPUPDIALOG				100
#define		TIMER_CHECK_LEFT_MOUSE_UP			101
#define		TIMER_CHECK_RIGHT_MOUSE_UP			102
#define		TIMER_SHOW_POPUP_DIALOG				103

#define		CHECK_MOUSE_UP_TIME					300
#define		MOVE_POPUP_DIALOG_TIME				10
#define		SHOW_POPUP_DIALOAD_TIME				1000